backend: sh -c 'cd ./trade-tariff-backend/ && bundle exec rails s'
worker: sh -c 'cd ./trade-tariff-backend/ && bundle exec sidekiq -C ./config/sidekiq.yml'
frontend: sh -c 'cd ./trade-tariff-frontend/ && bundle exec rails s -p 3001'
admin: sh -c 'cd ./trade-tariff-admin/ && bundle exec rails s -p 3002'
signonotron: sh -c 'cd ./signonotron2/ && bundle exec rails s -p 3003'